set(LUA_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
set(LUA_LIB "${CMAKE_CURRENT_LIST_DIR}/lua54.lib")
set(LUA_DLL "${CMAKE_CURRENT_LIST_DIR}/lua54.dll")
string(STRIP "${LUA_LIBRARIES}" LUA_LIBRARIES)